all: test_safequeue test2_safequeue
test_safequeue: test_safequeue.cpp safequeue.h
	g++ -o test_safequeue test_safequeue.cpp safequeue.h -lpthread
test2_safequeue: test2_safequeue.cpp safequeue.h
	g++ -o test2_safequeue test2_safequeue.cpp safequeue.h -lpthread